/**
 * Nạp kho vật tư thực tế cho cửa hàng sửa xe máy.
 * - Xóa các mặt hàng không phù hợp (xe nguyên chiếc, dữ liệu demo sai danh mục).
 * - Upsert theo item_code: sản phẩm có nhiều loại hàng (kích thước, dòng xe, dung tích...).
 *
 * Chạy: node src/scripts/seedMotorcycleInventory.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/database');
const InventoryItem = require('../models/InventoryItem.model');
const InventoryTransaction = require('../models/InventoryTransaction.model');

/** Mã hàng không thuộc kho phụ tùng — xóa hẳn. */
const REMOVE_CODES = [
  'NVX', // "Xe máy honda" — không phải vật tư kho
  'ITEM-001', // "Oil Filter" gắn sai danh mục TOOLS, tiếng Anh
];

/**
 * Mỗi phần tử = 1 loại hàng (1 document).
 * Các loại cùng product_name sẽ được UI nhóm thành 1 sản phẩm.
 */
const CATALOG = [
  // ---- Lốp & săm ----
  {
    product_name: 'Lốp Michelin City Grip',
    variant_name: '70/90-17',
    item_code: 'MIC-CG-7090',
    barcode: '8935001709017',
    category: 'TIRES_TUBES',
    brand: 'Michelin',
    car_model: 'Honda Vision',
    quality: 'PREMIUM',
    unit: 'cái',
    unit_price: 520000,
    quantity: 18,
    min_stock_level: 6,
    max_stock_level: 60,
    reorder_point: 10,
    supplier_name: 'Michelin Việt Nam',
    description: 'Lốp trước xe ga phổ thông, độ bám đường tốt khi trời mưa.',
  },
  {
    product_name: 'Lốp Michelin City Grip',
    variant_name: '80/90-17',
    item_code: 'MIC-CG-8090',
    barcode: '8935001709024',
    category: 'TIRES_TUBES',
    brand: 'Michelin',
    car_model: 'Honda Air Blade',
    quality: 'PREMIUM',
    unit: 'cái',
    unit_price: 590000,
    quantity: 12,
    min_stock_level: 5,
    max_stock_level: 50,
    reorder_point: 8,
    supplier_name: 'Michelin Việt Nam',
    description: 'Lốp Michelin City Grip size 80/90-17.',
  },
  {
    product_name: 'Lốp Michelin City Grip',
    variant_name: '90/90-17',
    item_code: 'MIC-CG-9090',
    barcode: '8935001709031',
    category: 'TIRES_TUBES',
    brand: 'Michelin',
    car_model: 'Honda SH',
    quality: 'PREMIUM',
    unit: 'cái',
    unit_price: 650000,
    quantity: 9,
    min_stock_level: 4,
    max_stock_level: 40,
    reorder_point: 6,
    supplier_name: 'Michelin Việt Nam',
    description: 'Lốp Michelin City Grip size 90/90-17.',
  },
  {
    product_name: 'Ruột xe IRC',
    variant_name: '70/90-17',
    item_code: 'IRC-IN-7090',
    category: 'TIRES_TUBES',
    brand: 'IRC',
    car_model: 'Honda Wave Alpha',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 85000,
    quantity: 40,
    min_stock_level: 15,
    max_stock_level: 120,
    reorder_point: 20,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Ruột xe số phổ thông.',
  },
  {
    product_name: 'Ruột xe IRC',
    variant_name: '80/90-14',
    item_code: 'IRC-IN-809014',
    category: 'TIRES_TUBES',
    brand: 'IRC',
    car_model: 'Honda Vision',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 90000,
    quantity: 28,
    min_stock_level: 12,
    max_stock_level: 100,
    reorder_point: 16,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Ruột xe tay ga size 14.',
  },

  // ---- Dầu nhớt ----
  {
    product_name: 'Dầu nhớt Motul 3100',
    variant_name: '10W30 0.8L',
    item_code: 'MOT-3100-1030-08',
    barcode: '3376405001234',
    category: 'LUBRICANTS',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'chai',
    unit_price: 145000,
    quantity: 36,
    min_stock_level: 12,
    max_stock_level: 150,
    reorder_point: 18,
    supplier_name: 'Motul Việt Nam',
    description: 'Nhớt bán tổng hợp cho xe số / xe ga phổ thông.',
  },
  {
    product_name: 'Dầu nhớt Motul 3100',
    variant_name: '10W40 0.8L',
    item_code: 'MOT-3100-1040-08',
    barcode: '3376405001241',
    category: 'LUBRICANTS',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'chai',
    unit_price: 155000,
    quantity: 42,
    min_stock_level: 12,
    max_stock_level: 150,
    reorder_point: 18,
    supplier_name: 'Motul Việt Nam',
    description: 'Nhớt Motul 3100 10W40 chai 0.8L.',
  },
  {
    product_name: 'Dầu nhớt Motul 3100',
    variant_name: '10W40 1L',
    item_code: 'MOT-3100-1040-1L',
    barcode: '3376405001258',
    category: 'LUBRICANTS',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'chai',
    unit_price: 185000,
    quantity: 24,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 14,
    supplier_name: 'Motul Việt Nam',
    description: 'Nhớt Motul 3100 10W40 chai 1L.',
  },
  {
    product_name: 'Dầu nhớt Honda SPX1',
    variant_name: '10W30 0.8L',
    item_code: 'HON-SPX1-1030',
    category: 'LUBRICANTS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'chai',
    unit_price: 135000,
    quantity: 50,
    min_stock_level: 15,
    max_stock_level: 200,
    reorder_point: 25,
    supplier_name: 'Honda Parts',
    description: 'Nhớt chính hãng Honda SPX1.',
  },
  {
    product_name: 'Dầu nhớt Honda SPX1',
    variant_name: '10W40 0.8L',
    item_code: 'HON-SPX1-1040',
    category: 'LUBRICANTS',
    brand: 'Honda',
    car_model: 'Honda Wave Alpha',
    quality: 'OEM',
    unit: 'chai',
    unit_price: 140000,
    quantity: 45,
    min_stock_level: 15,
    max_stock_level: 200,
    reorder_point: 25,
    supplier_name: 'Honda Parts',
    description: 'Nhớt chính hãng Honda SPX1 10W40.',
  },
  {
    product_name: 'Nước làm mát Motul',
    variant_name: 'Can 1L',
    item_code: 'MOT-COOL-1L',
    category: 'LUBRICANTS',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'can',
    unit_price: 95000,
    quantity: 20,
    min_stock_level: 8,
    max_stock_level: 80,
    reorder_point: 12,
    supplier_name: 'Motul Việt Nam',
    description: 'Nước làm mát động cơ xe máy.',
  },

  // ---- Hệ thống phanh ----
  {
    product_name: 'Má phanh Elig',
    variant_name: 'Trước Wave Alpha',
    item_code: 'ELIG-BP-WAV-F',
    category: 'BRAKE_SYSTEM',
    brand: 'Elig',
    car_model: 'Honda Wave Alpha',
    quality: 'STANDARD',
    unit: 'bộ',
    unit_price: 165000,
    quantity: 22,
    min_stock_level: 8,
    max_stock_level: 80,
    reorder_point: 12,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Má phanh trước cho Wave Alpha.',
  },
  {
    product_name: 'Má phanh Elig',
    variant_name: 'Sau Wave Alpha',
    item_code: 'ELIG-BP-WAV-R',
    category: 'BRAKE_SYSTEM',
    brand: 'Elig',
    car_model: 'Honda Wave Alpha',
    quality: 'STANDARD',
    unit: 'bộ',
    unit_price: 135000,
    quantity: 16,
    min_stock_level: 8,
    max_stock_level: 80,
    reorder_point: 12,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Má phanh sau cho Wave Alpha.',
  },
  {
    product_name: 'Má phanh Elig',
    variant_name: 'Trước Winner X',
    item_code: 'ELIG-BP-WIN-F',
    category: 'BRAKE_SYSTEM',
    brand: 'Elig',
    car_model: 'Honda Winner X',
    quality: 'PREMIUM',
    unit: 'bộ',
    unit_price: 220000,
    quantity: 10,
    min_stock_level: 5,
    max_stock_level: 50,
    reorder_point: 8,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Má phanh trước Winner X.',
  },
  {
    product_name: 'Má phanh Elig',
    variant_name: 'Sau Exciter',
    item_code: 'ELIG-BP-EXC-R',
    category: 'BRAKE_SYSTEM',
    brand: 'Elig',
    car_model: 'Yamaha Exciter',
    quality: 'PREMIUM',
    unit: 'bộ',
    unit_price: 195000,
    quantity: 8,
    min_stock_level: 5,
    max_stock_level: 50,
    reorder_point: 8,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Má phanh sau Exciter.',
  },
  {
    product_name: 'Dầu thắng Motul DOT 4',
    variant_name: 'Chai 100ml',
    item_code: 'MOT-DOT4-100',
    category: 'BRAKE_SYSTEM',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'chai',
    unit_price: 75000,
    quantity: 14,
    min_stock_level: 8,
    max_stock_level: 60,
    reorder_point: 10,
    supplier_name: 'Motul Việt Nam',
    description: 'Dầu thắng DOT 4 chai nhỏ.',
  },
  {
    product_name: 'Dầu thắng Motul DOT 4',
    variant_name: 'Chai 250ml',
    item_code: 'MOT-DOT4-250',
    category: 'BRAKE_SYSTEM',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'chai',
    unit_price: 145000,
    quantity: 9,
    min_stock_level: 5,
    max_stock_level: 40,
    reorder_point: 7,
    supplier_name: 'Motul Việt Nam',
    description: 'Dầu thắng DOT 4 chai 250ml.',
  },

  // ---- Lọc ----
  {
    product_name: 'Lọc gió Honda',
    variant_name: 'Vision',
    item_code: 'HON-AF-VIS',
    category: 'FILTERS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 85000,
    quantity: 35,
    min_stock_level: 12,
    max_stock_level: 120,
    reorder_point: 18,
    supplier_name: 'Honda Parts',
    description: 'Lọc gió chính hãng Vision.',
  },
  {
    product_name: 'Lọc gió Honda',
    variant_name: 'Wave Alpha',
    item_code: 'HON-AF-WAV',
    category: 'FILTERS',
    brand: 'Honda',
    car_model: 'Honda Wave Alpha',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 65000,
    quantity: 48,
    min_stock_level: 15,
    max_stock_level: 150,
    reorder_point: 22,
    supplier_name: 'Honda Parts',
    description: 'Lọc gió chính hãng Wave Alpha.',
  },
  {
    product_name: 'Lọc gió Honda',
    variant_name: 'Air Blade',
    item_code: 'HON-AF-AB',
    category: 'FILTERS',
    brand: 'Honda',
    car_model: 'Honda Air Blade',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 95000,
    quantity: 22,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 14,
    supplier_name: 'Honda Parts',
    description: 'Lọc gió chính hãng Air Blade.',
  },
  {
    product_name: 'Lọc nhớt',
    variant_name: 'Honda phổ thông',
    item_code: 'OF-HON-STD',
    category: 'FILTERS',
    brand: 'Honda',
    car_model: 'Dùng chung mọi xe',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 45000,
    quantity: 60,
    min_stock_level: 20,
    max_stock_level: 200,
    reorder_point: 30,
    supplier_name: 'Honda Parts',
    description: 'Lọc nhớt cho dòng Honda phổ thông.',
  },
  {
    product_name: 'Lọc nhớt',
    variant_name: 'Yamaha phổ thông',
    item_code: 'OF-YAM-STD',
    category: 'FILTERS',
    brand: 'Yamaha',
    car_model: 'Dùng chung mọi xe',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 48000,
    quantity: 40,
    min_stock_level: 15,
    max_stock_level: 150,
    reorder_point: 22,
    supplier_name: 'Yamaha Parts',
    description: 'Lọc nhớt cho dòng Yamaha phổ thông.',
  },

  // ---- Điện & ắc quy ----
  {
    product_name: 'Bugi NGK',
    variant_name: 'CPR7EA-9',
    item_code: 'NGK-CPR7EA9',
    barcode: '0874211012345',
    category: 'ELECTRICAL',
    brand: 'NGK',
    car_model: 'Honda Wave Alpha',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 55000,
    quantity: 70,
    min_stock_level: 20,
    max_stock_level: 200,
    reorder_point: 30,
    supplier_name: 'NGK Việt Nam',
    description: 'Bugi NGK cho Wave / Vision phổ thông.',
  },
  {
    product_name: 'Bugi NGK',
    variant_name: 'CPR8EA-9',
    item_code: 'NGK-CPR8EA9',
    barcode: '0874211012352',
    category: 'ELECTRICAL',
    brand: 'NGK',
    car_model: 'Honda Air Blade',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 65000,
    quantity: 45,
    min_stock_level: 15,
    max_stock_level: 150,
    reorder_point: 22,
    supplier_name: 'NGK Việt Nam',
    description: 'Bugi NGK cho Air Blade / Lead.',
  },
  {
    product_name: 'Bugi NGK',
    variant_name: 'CR8E',
    item_code: 'NGK-CR8E',
    barcode: '0874211012369',
    category: 'ELECTRICAL',
    brand: 'NGK',
    car_model: 'Yamaha Exciter',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 75000,
    quantity: 30,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 15,
    supplier_name: 'NGK Việt Nam',
    description: 'Bugi NGK cho Exciter / Winner.',
  },
  {
    product_name: 'Ắc quy GS',
    variant_name: '12V 5Ah',
    item_code: 'GS-BAT-5AH',
    category: 'ELECTRICAL',
    brand: 'GS',
    car_model: 'Honda Vision',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 420000,
    quantity: 14,
    min_stock_level: 5,
    max_stock_level: 40,
    reorder_point: 8,
    supplier_name: 'GS Battery',
    description: 'Ắc quy khô 12V 5Ah cho xe ga nhỏ.',
  },
  {
    product_name: 'Ắc quy GS',
    variant_name: '12V 7Ah',
    item_code: 'GS-BAT-7AH',
    category: 'ELECTRICAL',
    brand: 'GS',
    car_model: 'Honda SH',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 520000,
    quantity: 8,
    min_stock_level: 4,
    max_stock_level: 30,
    reorder_point: 6,
    supplier_name: 'GS Battery',
    description: 'Ắc quy khô 12V 7Ah.',
  },

  // ---- Đèn & gương ----
  {
    product_name: 'Gương chiếu hậu Honda',
    variant_name: 'Màu đen',
    item_code: 'HON-MIR-BLK',
    category: 'LIGHTS_MIRRORS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 95000,
    quantity: 26,
    min_stock_level: 10,
    max_stock_level: 80,
    reorder_point: 14,
    supplier_name: 'Honda Parts',
    description: 'Gương chiếu hậu màu đen.',
  },
  {
    product_name: 'Gương chiếu hậu Honda',
    variant_name: 'Màu trắng',
    item_code: 'HON-MIR-WHT',
    category: 'LIGHTS_MIRRORS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 98000,
    quantity: 18,
    min_stock_level: 8,
    max_stock_level: 60,
    reorder_point: 12,
    supplier_name: 'Honda Parts',
    description: 'Gương chiếu hậu màu trắng.',
  },
  {
    product_name: 'Gương chiếu hậu Honda',
    variant_name: 'Chrome',
    item_code: 'HON-MIR-CHR',
    category: 'LIGHTS_MIRRORS',
    brand: 'Honda',
    car_model: 'Honda Wave Alpha',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 110000,
    quantity: 15,
    min_stock_level: 6,
    max_stock_level: 50,
    reorder_point: 10,
    supplier_name: 'Honda Parts',
    description: 'Gương chiếu hậu mạ chrome.',
  },
  {
    product_name: 'Bóng đèn LED H4',
    variant_name: 'Ánh sáng trắng',
    item_code: 'LED-H4-WHT',
    category: 'LIGHTS_MIRRORS',
    brand: 'Philips',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'bộ',
    unit_price: 280000,
    quantity: 16,
    min_stock_level: 6,
    max_stock_level: 50,
    reorder_point: 10,
    supplier_name: 'Điện xe Miền Nam',
    description: 'Bóng LED H4 ánh sáng trắng.',
  },
  {
    product_name: 'Bóng đèn LED H4',
    variant_name: 'Ánh sáng vàng',
    item_code: 'LED-H4-YEL',
    category: 'LIGHTS_MIRRORS',
    brand: 'Philips',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'bộ',
    unit_price: 280000,
    quantity: 11,
    min_stock_level: 5,
    max_stock_level: 40,
    reorder_point: 8,
    supplier_name: 'Điện xe Miền Nam',
    description: 'Bóng LED H4 ánh sáng vàng.',
  },
  {
    product_name: 'Xi nhan LED',
    variant_name: 'Vuông nhỏ',
    item_code: 'SIG-LED-SQ',
    category: 'LIGHTS_MIRRORS',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'BUDGET',
    unit: 'cặp',
    unit_price: 120000,
    quantity: 20,
    min_stock_level: 8,
    max_stock_level: 60,
    reorder_point: 12,
    supplier_name: 'Điện xe Miền Nam',
    description: 'Cặp xi nhan LED dạng vuông.',
  },

  // ---- Truyền động ----
  {
    product_name: 'Dây curoa Gates',
    variant_name: 'Vision',
    item_code: 'GAT-BELT-VIS',
    category: 'TRANSMISSION',
    brand: 'Gates',
    car_model: 'Honda Vision',
    quality: 'PREMIUM',
    unit: 'cái',
    unit_price: 320000,
    quantity: 18,
    min_stock_level: 8,
    max_stock_level: 60,
    reorder_point: 12,
    supplier_name: 'Gates Việt Nam',
    description: 'Dây curoa Gates cho Vision.',
  },
  {
    product_name: 'Dây curoa Gates',
    variant_name: 'Air Blade',
    item_code: 'GAT-BELT-AB',
    category: 'TRANSMISSION',
    brand: 'Gates',
    car_model: 'Honda Air Blade',
    quality: 'PREMIUM',
    unit: 'cái',
    unit_price: 350000,
    quantity: 14,
    min_stock_level: 6,
    max_stock_level: 50,
    reorder_point: 10,
    supplier_name: 'Gates Việt Nam',
    description: 'Dây curoa Gates cho Air Blade.',
  },
  {
    product_name: 'Dây curoa Gates',
    variant_name: 'Lead',
    item_code: 'GAT-BELT-LEAD',
    category: 'TRANSMISSION',
    brand: 'Gates',
    car_model: 'Honda Lead',
    quality: 'PREMIUM',
    unit: 'cái',
    unit_price: 340000,
    quantity: 10,
    min_stock_level: 5,
    max_stock_level: 40,
    reorder_point: 8,
    supplier_name: 'Gates Việt Nam',
    description: 'Dây curoa Gates cho Lead.',
  },
  {
    product_name: 'Nhông sên dĩa DID',
    variant_name: 'Wave 14T-36T',
    item_code: 'DID-NSD-WAV',
    category: 'TRANSMISSION',
    brand: 'DID',
    car_model: 'Honda Wave Alpha',
    quality: 'PREMIUM',
    unit: 'bộ',
    unit_price: 380000,
    quantity: 12,
    min_stock_level: 5,
    max_stock_level: 40,
    reorder_point: 8,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Bộ nhông sên dĩa DID cho Wave.',
  },
  {
    product_name: 'Nhông sên dĩa DID',
    variant_name: 'Exciter 15T-42T',
    item_code: 'DID-NSD-EXC',
    category: 'TRANSMISSION',
    brand: 'DID',
    car_model: 'Yamaha Exciter',
    quality: 'PREMIUM',
    unit: 'bộ',
    unit_price: 520000,
    quantity: 7,
    min_stock_level: 3,
    max_stock_level: 30,
    reorder_point: 5,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Bộ nhông sên dĩa DID cho Exciter.',
  },

  // ---- Giảm xóc ----
  {
    product_name: 'Phuộc sau KYB',
    variant_name: 'Wave Alpha',
    item_code: 'KYB-RS-WAV',
    category: 'SUSPENSION',
    brand: 'KYB',
    car_model: 'Honda Wave Alpha',
    quality: 'PREMIUM',
    unit: 'cặp',
    unit_price: 650000,
    quantity: 6,
    min_stock_level: 3,
    max_stock_level: 24,
    reorder_point: 4,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Phuộc sau KYB cho Wave Alpha.',
  },
  {
    product_name: 'Phuộc sau KYB',
    variant_name: 'Vision',
    item_code: 'KYB-RS-VIS',
    category: 'SUSPENSION',
    brand: 'KYB',
    car_model: 'Honda Vision',
    quality: 'PREMIUM',
    unit: 'cặp',
    unit_price: 720000,
    quantity: 5,
    min_stock_level: 2,
    max_stock_level: 20,
    reorder_point: 3,
    supplier_name: 'Phụ tùng Miền Nam',
    description: 'Phuộc sau KYB cho Vision.',
  },

  // ---- Dàn áo ----
  {
    product_name: 'Ốp sườn Vision',
    variant_name: 'Đỏ',
    item_code: 'BODY-VIS-RED',
    category: 'BODY_PARTS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 450000,
    quantity: 4,
    min_stock_level: 2,
    max_stock_level: 16,
    reorder_point: 3,
    supplier_name: 'Honda Parts',
    description: 'Bộ ốp sườn Vision màu đỏ.',
  },
  {
    product_name: 'Ốp sườn Vision',
    variant_name: 'Đen',
    item_code: 'BODY-VIS-BLK',
    category: 'BODY_PARTS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 450000,
    quantity: 5,
    min_stock_level: 2,
    max_stock_level: 16,
    reorder_point: 3,
    supplier_name: 'Honda Parts',
    description: 'Bộ ốp sườn Vision màu đen.',
  },
  {
    product_name: 'Ốp sườn Vision',
    variant_name: 'Trắng',
    item_code: 'BODY-VIS-WHT',
    category: 'BODY_PARTS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 450000,
    quantity: 3,
    min_stock_level: 2,
    max_stock_level: 16,
    reorder_point: 3,
    supplier_name: 'Honda Parts',
    description: 'Bộ ốp sườn Vision màu trắng.',
  },
  {
    product_name: 'Yên xe Wave',
    variant_name: 'Tiêu chuẩn',
    item_code: 'SEAT-WAV-STD',
    category: 'BODY_PARTS',
    brand: 'Honda',
    car_model: 'Honda Wave Alpha',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 280000,
    quantity: 6,
    min_stock_level: 2,
    max_stock_level: 20,
    reorder_point: 3,
    supplier_name: 'Honda Parts',
    description: 'Yên xe Wave Alpha chính hãng.',
  },

  // ---- Phụ kiện ----
  {
    product_name: 'Baga sau',
    variant_name: 'Vision',
    item_code: 'ACC-BAG-VIS',
    category: 'ACCESSORIES',
    brand: 'Generic',
    car_model: 'Honda Vision',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 185000,
    quantity: 12,
    min_stock_level: 4,
    max_stock_level: 40,
    reorder_point: 6,
    supplier_name: 'Phụ kiện MotoCare',
    description: 'Baga sau lắp Vision.',
  },
  {
    product_name: 'Baga sau',
    variant_name: 'Wave',
    item_code: 'ACC-BAG-WAV',
    category: 'ACCESSORIES',
    brand: 'Generic',
    car_model: 'Honda Wave Alpha',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 165000,
    quantity: 10,
    min_stock_level: 4,
    max_stock_level: 40,
    reorder_point: 6,
    supplier_name: 'Phụ kiện MotoCare',
    description: 'Baga sau lắp Wave.',
  },
  {
    product_name: 'Giá đỡ điện thoại',
    variant_name: 'Kẹp gương',
    item_code: 'ACC-PHONE-MIR',
    category: 'ACCESSORIES',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'BUDGET',
    unit: 'cái',
    unit_price: 75000,
    quantity: 25,
    min_stock_level: 8,
    max_stock_level: 80,
    reorder_point: 12,
    supplier_name: 'Phụ kiện MotoCare',
    description: 'Giá đỡ điện thoại kẹp gương.',
  },
  {
    product_name: 'Giá đỡ điện thoại',
    variant_name: 'Kẹp ghi đông',
    item_code: 'ACC-PHONE-BAR',
    category: 'ACCESSORIES',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'BUDGET',
    unit: 'cái',
    unit_price: 85000,
    quantity: 20,
    min_stock_level: 8,
    max_stock_level: 80,
    reorder_point: 12,
    supplier_name: 'Phụ kiện MotoCare',
    description: 'Giá đỡ điện thoại kẹp ghi đông.',
  },

  // ---- Vật tư tiêu hao ----
  {
    product_name: 'Ốc vít inox',
    variant_name: 'M6',
    item_code: 'CON-BOLT-M6',
    category: 'CONSUMABLES',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'hộp',
    unit_price: 35000,
    quantity: 40,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 15,
    supplier_name: 'Vật tư xưởng',
    description: 'Hộp ốc vít inox M6.',
  },
  {
    product_name: 'Ốc vít inox',
    variant_name: 'M8',
    item_code: 'CON-BOLT-M8',
    category: 'CONSUMABLES',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'hộp',
    unit_price: 45000,
    quantity: 35,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 15,
    supplier_name: 'Vật tư xưởng',
    description: 'Hộp ốc vít inox M8.',
  },
  {
    product_name: 'Keo dán ron',
    variant_name: 'Tuýp 70g',
    item_code: 'CON-SEAL-70',
    category: 'CONSUMABLES',
    brand: 'ThreeBond',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'tuýp',
    unit_price: 65000,
    quantity: 22,
    min_stock_level: 8,
    max_stock_level: 60,
    reorder_point: 12,
    supplier_name: 'Vật tư xưởng',
    description: 'Keo dán ron động cơ.',
  },
  {
    product_name: 'Dây rút nhựa',
    variant_name: 'Gói 100 cái',
    item_code: 'CON-TIE-100',
    category: 'CONSUMABLES',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'BUDGET',
    unit: 'gói',
    unit_price: 25000,
    quantity: 30,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 15,
    supplier_name: 'Vật tư xưởng',
    description: 'Dây rút nhựa gói 100 cái.',
  },
  {
    product_name: 'Dung dịch rửa xe',
    variant_name: 'Can 1L',
    item_code: 'WASH-1L',
    category: 'CONSUMABLES',
    brand: 'MotoCare',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'can',
    unit_price: 95000,
    quantity: 18,
    min_stock_level: 6,
    max_stock_level: 50,
    reorder_point: 10,
    supplier_name: 'MotoCare Detailing',
    description: 'Dung dịch rửa xe và vệ sinh dàn áo.',
  },
  {
    product_name: 'Dung dịch rửa xe',
    variant_name: 'Can 5L',
    item_code: 'WASH-5L',
    category: 'CONSUMABLES',
    brand: 'MotoCare',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'can',
    unit_price: 380000,
    quantity: 6,
    min_stock_level: 3,
    max_stock_level: 20,
    reorder_point: 4,
    supplier_name: 'MotoCare Detailing',
    description: 'Dung dịch rửa xe can lớn 5L.',
  },

  // ---- Phụ tùng động cơ ----
  {
    product_name: 'Piston',
    variant_name: 'Wave 50mm',
    item_code: 'ENG-PIST-WAV50',
    category: 'ENGINE_PARTS',
    brand: 'Honda',
    car_model: 'Honda Wave Alpha',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 380000,
    quantity: 8,
    min_stock_level: 3,
    max_stock_level: 30,
    reorder_point: 5,
    supplier_name: 'Honda Parts',
    description: 'Bộ piston Wave 50mm.',
  },
  {
    product_name: 'Piston',
    variant_name: 'Exciter 62mm',
    item_code: 'ENG-PIST-EXC62',
    category: 'ENGINE_PARTS',
    brand: 'Yamaha',
    car_model: 'Yamaha Exciter',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 520000,
    quantity: 5,
    min_stock_level: 2,
    max_stock_level: 20,
    reorder_point: 3,
    supplier_name: 'Yamaha Parts',
    description: 'Bộ piston Exciter 62mm.',
  },
  {
    product_name: 'Bộ nồi',
    variant_name: 'Vision',
    item_code: 'ENG-CLUTCH-VIS',
    category: 'ENGINE_PARTS',
    brand: 'Honda',
    car_model: 'Honda Vision',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 780000,
    quantity: 4,
    min_stock_level: 2,
    max_stock_level: 16,
    reorder_point: 3,
    supplier_name: 'Honda Parts',
    description: 'Bộ nồi Vision chính hãng.',
  },
  {
    product_name: 'Bộ nồi',
    variant_name: 'Air Blade',
    item_code: 'ENG-CLUTCH-AB',
    category: 'ENGINE_PARTS',
    brand: 'Honda',
    car_model: 'Honda Air Blade',
    quality: 'OEM',
    unit: 'bộ',
    unit_price: 850000,
    quantity: 3,
    min_stock_level: 2,
    max_stock_level: 12,
    reorder_point: 3,
    supplier_name: 'Honda Parts',
    description: 'Bộ nồi Air Blade chính hãng.',
  },

  // ---- Dụng cụ ----
  {
    product_name: 'Bộ đồ nghề sửa xe',
    variant_name: '40 chi tiết',
    item_code: 'TOOL-SET-40',
    category: 'TOOLS_EQUIPMENT',
    brand: 'Tolsen',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'bộ',
    unit_price: 550000,
    quantity: 6,
    min_stock_level: 2,
    max_stock_level: 15,
    reorder_point: 3,
    supplier_name: 'Công cụ xưởng',
    description: 'Bộ đồ nghề cơ bản 40 chi tiết cho thợ sửa xe.',
  },
  {
    product_name: 'Kích nâng xe máy',
    variant_name: 'Tiêu chuẩn',
    item_code: 'TOOL-JACK-STD',
    category: 'TOOLS_EQUIPMENT',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'cái',
    unit_price: 1200000,
    quantity: 2,
    min_stock_level: 1,
    max_stock_level: 5,
    reorder_point: 1,
    supplier_name: 'Công cụ xưởng',
    description: 'Kích nâng xe máy dùng trong xưởng.',
  },

  // ---- Chuẩn hóa các mã cũ còn dùng (giữ mã, sửa danh mục / tên nhóm) ----
  {
    product_name: 'Dầu nhớt cửa hàng',
    variant_name: '10W40',
    item_code: 'OIL-10W40',
    category: 'LUBRICANTS',
    brand: 'Castrol',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'lít',
    unit_price: 80000,
    quantity: 50,
    min_stock_level: 20,
    max_stock_level: 200,
    reorder_point: 30,
    supplier_name: 'Công ty Dầu nhớt ABC',
    description: 'Dầu nhớt 10W40 dùng bảo dưỡng phổ thông.',
  },
  {
    product_name: 'Má phanh cửa hàng',
    variant_name: 'Trước Wave',
    item_code: 'BP-FRONT',
    category: 'BRAKE_SYSTEM',
    brand: 'Elig',
    car_model: 'Honda Wave Alpha',
    quality: 'STANDARD',
    unit: 'bộ',
    unit_price: 150000,
    quantity: 15,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 20,
    supplier_name: 'Phụ tùng XYZ',
    description: 'Má phanh trước Wave.',
  },
  {
    product_name: 'Má phanh cửa hàng',
    variant_name: 'Sau Wave',
    item_code: 'BP-REAR',
    category: 'BRAKE_SYSTEM',
    brand: 'Elig',
    car_model: 'Honda Wave Alpha',
    quality: 'STANDARD',
    unit: 'bộ',
    unit_price: 120000,
    quantity: 8,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_point: 15,
    supplier_name: 'Phụ tùng XYZ',
    description: 'Má phanh sau Wave.',
  },
  {
    product_name: 'Lọc gió phổ thông',
    variant_name: 'Đa dụng',
    item_code: 'AF-001',
    category: 'FILTERS',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'BUDGET',
    unit: 'cái',
    unit_price: 50000,
    quantity: 100,
    min_stock_level: 30,
    max_stock_level: 300,
    reorder_point: 50,
    supplier_name: 'Phụ tùng XYZ',
    description: 'Lọc gió đa dụng cho xe phổ thông.',
  },
  {
    product_name: 'Bugi NGK',
    variant_name: 'Phổ thông cũ',
    item_code: 'SP-NGK',
    category: 'ELECTRICAL',
    brand: 'NGK',
    car_model: 'Dùng chung mọi xe',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 40000,
    quantity: 78,
    min_stock_level: 20,
    max_stock_level: 200,
    reorder_point: 40,
    supplier_name: 'Phụ tùng XYZ',
    description: 'Bugi NGK tồn kho cũ — nên chuyển dần sang mã theo từng loại bugi.',
  },
  {
    product_name: 'Dầu thắng Motul DOT 4',
    variant_name: 'Chai kho cũ',
    item_code: 'BF-001',
    category: 'BRAKE_SYSTEM',
    brand: 'Motul',
    car_model: 'Dùng chung mọi xe',
    quality: 'PREMIUM',
    unit: 'chai',
    unit_price: 60000,
    quantity: 5,
    min_stock_level: 10,
    max_stock_level: 50,
    reorder_point: 15,
    supplier_name: 'Công ty Dầu nhớt ABC',
    description: 'Dầu thắng DOT 4 — tồn kho cũ.',
  },
  {
    product_name: 'Dây curoa phổ thông',
    variant_name: 'Xe tay ga',
    item_code: 'BELT-001',
    category: 'TRANSMISSION',
    brand: 'Generic',
    car_model: 'Dùng chung mọi xe',
    quality: 'BUDGET',
    unit: 'cái',
    unit_price: 180000,
    quantity: 25,
    min_stock_level: 15,
    max_stock_level: 80,
    reorder_point: 25,
    supplier_name: 'Phụ tùng XYZ',
    description: 'Dây curoa phổ thông xe tay ga.',
  },
  {
    product_name: 'Bộ đồ nghề sửa xe',
    variant_name: 'Cơ bản cũ',
    item_code: 'TOOL-SET-01',
    category: 'TOOLS_EQUIPMENT',
    brand: 'Tolsen',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'bộ',
    unit_price: 500000,
    quantity: 10,
    min_stock_level: 5,
    max_stock_level: 20,
    reorder_point: 8,
    supplier_name: 'Công cụ DEF',
    description: 'Bộ dụng cụ sửa chữa cơ bản.',
  },
  {
    product_name: 'Dầu nhớt cửa hàng',
    variant_name: '10W40 (staff)',
    item_code: 'STAFF-OIL-10W40',
    category: 'LUBRICANTS',
    brand: 'Castrol',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'chai',
    unit_price: 120000,
    quantity: 24,
    min_stock_level: 8,
    max_stock_level: 100,
    reorder_point: 10,
    supplier_name: 'MotoCare Parts',
    description: 'Nhớt bán tổng hợp dùng bảo dưỡng phổ thông.',
  },
  {
    product_name: 'Bugi NGK',
    variant_name: 'Staff test',
    item_code: 'STAFF-SPARK-NGK',
    category: 'ELECTRICAL',
    brand: 'NGK',
    car_model: 'Dùng chung mọi xe',
    quality: 'OEM',
    unit: 'cái',
    unit_price: 65000,
    quantity: 18,
    min_stock_level: 10,
    max_stock_level: 120,
    reorder_point: 12,
    supplier_name: 'MotoCare Parts',
    description: 'Bugi NGK dùng trong dữ liệu test staff.',
  },
  {
    product_name: 'Dung dịch rửa xe',
    variant_name: 'Can staff',
    item_code: 'STAFF-WASH-SOLUTION',
    category: 'CONSUMABLES',
    brand: 'MotoCare',
    car_model: 'Dùng chung mọi xe',
    quality: 'STANDARD',
    unit: 'can',
    unit_price: 95000,
    quantity: 3,
    min_stock_level: 3,
    max_stock_level: 30,
    reorder_point: 4,
    supplier_name: 'MotoCare Detailing',
    description: 'Dung dịch rửa xe và vệ sinh dàn áo.',
  },
];

function buildDoc(item) {
  const variant = item.variant_name || '';
  return {
    ...item,
    item_name: variant ? `${item.product_name} - ${variant}` : item.product_name,
    barcode: item.barcode || '',
    cost_price: item.cost_price ?? Math.round((item.unit_price || 0) * 0.7),
    location: item.location || { warehouse: 'Kho chính', shelf: '', bin: '' },
    is_active: true,
  };
}

async function removeUnsuitable() {
  const items = await InventoryItem.find({ item_code: { $in: REMOVE_CODES } }).select('_id item_code item_name');
  if (!items.length) {
    console.log('Không có mặt hàng không phù hợp cần xóa.');
    return 0;
  }

  const ids = items.map((item) => item._id);
  await InventoryTransaction.deleteMany({ inventory_item_id: { $in: ids } });
  await InventoryItem.deleteMany({ _id: { $in: ids } });

  items.forEach((item) => console.log(`  ✕ Đã xóa: ${item.item_code} — ${item.item_name}`));
  return items.length;
}

async function upsertCatalog() {
  let created = 0;
  let updated = 0;

  for (const raw of CATALOG) {
    const doc = buildDoc(raw);
    const existing = await InventoryItem.findOne({ item_code: doc.item_code });
    if (existing) {
      const keepQty = existing.quantity;
      Object.assign(existing, doc, { quantity: keepQty });
      await existing.save();
      updated += 1;
    } else {
      await InventoryItem.create(doc);
      created += 1;
    }
  }

  return { created, updated };
}

async function main() {
  await connectDB();
  console.log('🧹 Xóa vật tư không phù hợp...');
  const removed = await removeUnsuitable();

  console.log('📦 Nạp / cập nhật danh mục kho cửa hàng sửa xe máy...');
  const { created, updated } = await upsertCatalog();

  const total = await InventoryItem.countDocuments();
  const products = await InventoryItem.distinct('product_name', {
    product_name: { $nin: [null, ''] },
  });

  console.log('\n✅ Hoàn tất');
  console.log(`  - Đã xóa: ${removed}`);
  console.log(`  - Đã tạo mới: ${created}`);
  console.log(`  - Đã cập nhật: ${updated}`);
  console.log(`  - Tổng mã hàng trong kho: ${total}`);
  console.log(`  - Tổng sản phẩm (nhóm): ${products.length}`);

  await mongoose.disconnect();
}

main().catch((error) => {
  console.error('❌ Lỗi seed kho:', error);
  process.exit(1);
});
